[package]
name = "yadns"
version = "0.3.5"
authors = ["zyj"]
edition = "2021"

[features]
default = ["default-rustls"]

default-tcp_udp = []
default-rustls = ["dns-over-tls", "dns-over-https"]
default-openssl = ["dns-over-tls", "openssl"]

dns-over-tls = ["hickory-resolver"]
dns-over-https = ["hickory-resolver"]

[dependencies]
async-recursion = "1"
async-trait = "0.1"
clap = { version = "4", features = ["derive"] }
failure = "0.1"
futures = { version = "0.3", default-features = false }
hickory-proto = "0.24"
hickory-resolver = { version = "0.24", default-features = false, features = ["tokio-runtime"] }
hickory-server = "0.24"
ipnet = "2"
iprange = "0.6"
once_cell = "1"
publicsuffix = "2"
regex = "1"
serde = "1"
serde_derive = "1"
slog = "2"
slog-async = "2"
slog-term = "2"
tokio = "1"
toml = "0.8"

[target.'cfg(any(target_arch = "mips", target_arch = "mips64"))'.dependencies]
hickory-resolver = { version = "0.24", default-features = false, features = ["dns-over-openssl"], optional = true }
openssl = { version = "0.10", features = ["vendored"], optional = true }

[target.'cfg(not(any(target_arch = "mips", target_arch = "mips64")))'.dependencies]
hickory-resolver = { version = "0.24", default-features = false, features = ["dns-over-https-rustls"], optional = true }

[profile.release]
opt-level = 3
lto = true
# codegen-units = 1
panic = "abort"
strip = "symbols"
