[package]
name = "yadns"
version = "0.3.5"
authors = ["zyj"]
edition = "2021"

[features]
default = ["default-rustls"]

default-tcp_udp = []
default-rustls = ["dns-over-tls", "dns-over-https"]
default-openssl = ["dns-over-tls", "openssl"]

dns-over-tls = ["hickory-resolver"]
dns-over-https = ["hickory-resolver"]

[dependencies]
anyhow = "1.0.75"
async-recursion = "1.0.5"
async-trait = "0.1.74"
clap = { version = "4.4.6", features = ["derive"] }
failure = "0.1.8"
futures = "0.3.28"
hickory-proto = "0.24.0"
hickory-resolver = { version = "0.24.0", default-features = false, features = ["tokio-runtime"] }
hickory-server = "0.24.0"
ipnet = "2.8.0"
iprange = "0.6.7"
lazy_static = "1.4.0"
once_cell = "1.18.0"
publicsuffix = "2.2.3"
regex = "1.10.2"
serde = "1.0.189"
serde_derive = "1.0.189"
slog = "2.7.0"
slog-async = "2.8.0"
slog-term = "2.9.0"
tokio = "1.33.0"
toml = "0.7.8"

[target.'cfg(any(target_arch = "mips", target_arch = "mips64"))'.dependencies]
hickory-resolver = { version = "0.24.0", default-features = false, features = ["dns-over-openssl"], optional = true }
openssl = { version = "0.10", features = ["vendored"], optional = true }

[target.'cfg(not(any(target_arch = "mips", target_arch = "mips64")))'.dependencies]
hickory-resolver = { version = "0.24.0", default-features = false, features = ["dns-over-https-rustls"], optional = true }

[profile.release]
opt-level = 3
lto = true
# codegen-units = 1
panic = "abort"
strip = "symbols"
