name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        feature:
          - default
          - default-doh
          - default-dot
          - default-doh3
          - default-quic
          - default-tcp_udp
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --no-default-features --features ${{ matrix.feature }}
      - name: Run tests
        run: cargo test --verbose --no-default-features --features ${{ matrix.feature }}
