name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        feature:
          - default-doh-rustls
          # - default-dot-openssl
          - default-dot-rustls
          - default-doh3-rustls
          - default-tcp_udp
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install deps
        if: ${{ matrix.feature == 'default-dot-openssl' }}
        run: |
          sudo apt update && sudo apt install -y pkg-config libssl-dev
      - name: Build
        run: cargo build --verbose --no-default-features --features ${{ matrix.feature }}
      - name: Run tests
        run: cargo test --verbose --no-default-features --features ${{ matrix.feature }}
